# Travis CI script

language: c

os:
- linux

sudo: false

env:

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8

before_install:
# - make check

#before_script:
#- ./configure

script: ./ci_build.sh
