# Travis CI script

language: c

os:
- linux

sudo: false

env:

addons:
#  apt:
#    packages:
#    - uuid-dev

before_install:
- make regressions

before_script:
- ./configure

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh
